name: Run unit tests

"on":
  - push

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: check out repository
        uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: lint with flake8
        run: |
          flake8 todotxtio.py

      - name: run unit tests
        run: |
          pytest
